In [275]:
import pandas as pd
import numpy as np

In [276]:
data=[1,2,3,4,5]
sa=pd.Series(data)
sa

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [277]:
data=[[1],[2]]
sa=pd.Series(data)
sa

0    [1]
1    [2]
dtype: object

In [278]:
data=[[1,2],[3,4]]
sa=pd.DataFrame(data,columns=['anand','wert'])
sa

   anand  wert
0      1     2
1      3     4

In [279]:
data=[[1,2],[3,4]]
sa=pd.DataFrame(data,columns=['anand','wert'],index=[20,30])
sa

    anand  wert
20      1     2
30      3     4

In [280]:
df=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/main/Datasets-Practice/titanic.csv')

In [281]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [282]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [283]:
df.tail()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [284]:
df.tail(10)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1299,3,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C,0
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1301,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C,0
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [285]:
df.info()
#it will display the information of each column that is not null count and datatype of entair column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [286]:
df.describe() #it will give statical information if numercal based column

,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [287]:
df.shape #total no. of columns and rows in tuple datatype

(1309, 11)

In [288]:
df.columns #it will provide only column names  available in data set

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

In [289]:
df.dtypes #it will display only the datatypes

pclass        int64
name         object
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
cabin        object
embarked     object
survived      int64
dtype: object

In [290]:
# SLICING extracting the grounp of values
#df[startindex:endindex-+1:updating ]    used to extract datasets
#df['col_name'][si:ed-+1:updation]    used to extract the dataset with respect to only column
#df[['col_name1','col_name2']][si:ed-+1:updation]    used to extract the dataset with respect one or more column

df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [291]:
df[7:17]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
10,1,"Astor, Col. John Jacob",male,47.0,1,0,PC 17757,227.5250,C62 C64,C,0
11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
16,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,0

In [292]:
df[7:17:2]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0

In [293]:
df['cabin'][1:10:2]

1    C22 C26
3    C22 C26
5        E12
7        A36
9        NaN
Name: cabin, dtype: object

In [294]:
df['cabin'][::]

0            B5
1       C22 C26
2       C22 C26
3       C22 C26
4       C22 C26
         ...
1304        NaN
1305        NaN
1306        NaN
1307        NaN
1308        NaN
Name: cabin, Length: 1309, dtype: object

In [295]:
df[['name','embarked','age']][1:10:2]

                                   name embarked      age
1        Allison, Master. Hudson Trevor        S   0.9167
3  Allison, Mr. Hudson Joshua Creighton        S  30.0000
5                   Anderson, Mr. Harry        S  48.0000
7                Andrews, Mr. Thomas Jr        S  39.0000
9               Artagaveytia, Mr. Ramon        C  71.0000

In [296]:
# loc +> help us to slice throught the column
# df.loc[rowslice,'col_name'] with reference to one col_name
# df.loc[rowslice,['col_name1','col_name2']] with reference to more then one col_name
df.loc[1:10,['name']]

                                               name
1                    Allison, Master. Hudson Trevor
2                      Allison, Miss. Helen Loraine
3              Allison, Mr. Hudson Joshua Creighton
4   Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
5                               Anderson, Mr. Harry
6                 Andrews, Miss. Kornelia Theodosia
7                            Andrews, Mr. Thomas Jr
8     Appleton, Mrs. Edward Dale (Charlotte Lamson)
9                           Artagaveytia, Mr. Ramon
10                           Astor, Col. John Jacob

In [297]:
df.loc[1:30,['name','age']]

                                                 name      age
1                      Allison, Master. Hudson Trevor   0.9167
2                        Allison, Miss. Helen Loraine   2.0000
3                Allison, Mr. Hudson Joshua Creighton  30.0000
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000
5                                 Anderson, Mr. Harry  48.0000
6                   Andrews, Miss. Kornelia Theodosia  63.0000
7                              Andrews, Mr. Thomas Jr  39.0000
8       Appleton, Mrs. Edward Dale (Charlotte Lamson)  53.0000
9                             Artagaveytia, Mr. Ramon  71.0000
10                             Astor, Col. John Jacob  47.0000
11  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0000
12                      Aubart, Mme. Leontine Pauline  24.0000
13                       Barber, Miss. Ellen "Nellie"  26.0000
14               Barkworth, Mr. Algernon Henry Wilson  80.0000
15                                Baumann, Mr. John D      NaN
16                           Baxter, Mr. Quigg Edmond  24.0000
17    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  50.0000
18                              Bazzani, Miss. Albina  32.0000
19                               Beattie, Mr. Thomson  36.0000
20                      Beckwith, Mr. Richard Leonard  37.0000
21   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0000
22                              Behr, Mr. Karl Howell  26.0000
23                              Bidois, Miss. Rosalie  42.0000
24                                  Bird, Miss. Ellen  29.0000
25                                Birnbaum, Mr. Jakob  25.0000
26                            Bishop, Mr. Dickinson H  25.0000
27            Bishop, Mrs. Dickinson H (Helen Walton)  19.0000
28                             Bissette, Miss. Amelia  35.0000
29          Bjornstrom-Steffansson, Mr. Mauritz Hakan  28.0000
30                       Blackwell, Mr. Stephen Weart  45.0000

In [298]:
df[::-1] #it will give the dataset in reverse order

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1

In [299]:
# iloc ---- it will help us to slice throught both rows and columns
# df.iloc[rowslice,'col_name'] with reference to one col_name
# df.iloc[rowslice,['col_name1','col_name2']] with reference to more then one col_name

df.iloc[10:20,5:7] #10:20 rows,5:7 column

    parch    ticket
10      0  PC 17757
11      0  PC 17757
12      0  PC 17477
13      0     19877
14      0     27042
15      0  PC 17318
16      1  PC 17558
17      1  PC 17558
18      0     11813
19      0     13050

In [300]:
df.iloc[[1,2,3,4,5],[0,1,2,3]]

   pclass                                             name     sex      age
1       1                   Allison, Master. Hudson Trevor    male   0.9167
2       1                     Allison, Miss. Helen Loraine  female   2.0000
3       1             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000
5       1                              Anderson, Mr. Harry    male  48.0000

In [301]:
df.iloc[::2,::2] #use to extract data in even index

      pclass     sex  sibsp  ticket    cabin  survived
0          1  female      0   24160       B5         1
2          1  female      1  113781  C22 C26         0
4          1  female      1  113781  C22 C26         0
6          1  female      1   13502       D7         1
8          1  female      2   11769     C101         1
...      ...     ...    ...     ...      ...       ...
1300       3  female      1    2659      NaN         1
1302       3    male      0    2647      NaN         0
1304       3  female      1    2665      NaN         0
1306       3    male      0    2656      NaN         0
1308       3    male      0  315082      NaN         0

[655 rows x 6 columns]

In [302]:
df.iloc[1::2,1::2] #use to extract data in odd index

                                      name      age  parch      fare embarked
1           Allison, Master. Hudson Trevor   0.9167      2  151.5500        S
3     Allison, Mr. Hudson Joshua Creighton  30.0000      2  151.5500        S
5                      Anderson, Mr. Harry  48.0000      0   26.5500        S
7                   Andrews, Mr. Thomas Jr  39.0000      0    0.0000        S
9                  Artagaveytia, Mr. Ramon  71.0000      0   49.5042        C
...                                    ...      ...    ...       ...      ...
1299                   Yasbeck, Mr. Antoni  27.0000      0   14.4542        C
1301                  Youseff, Mr. Gerious  45.5000      0    7.2250        C
1303                 Yousseff, Mr. Gerious      NaN      0   14.4583        C
1305                 Zabour, Miss. Thamine      NaN      0   14.4542        C
1307                   Zakarian, Mr. Ortin  27.0000      0    7.2250        C

[654 rows x 5 columns]

In [303]:
df.iloc[1::2,1::3]

                                      name  sibsp      fare  survived
1           Allison, Master. Hudson Trevor      1  151.5500         1
3     Allison, Mr. Hudson Joshua Creighton      1  151.5500         0
5                      Anderson, Mr. Harry      0   26.5500         1
7                   Andrews, Mr. Thomas Jr      0    0.0000         0
9                  Artagaveytia, Mr. Ramon      0   49.5042         0
...                                    ...    ...       ...       ...
1299                   Yasbeck, Mr. Antoni      1   14.4542         0
1301                  Youseff, Mr. Gerious      0    7.2250         0
1303                 Yousseff, Mr. Gerious      0   14.4583         0
1305                 Zabour, Miss. Thamine      1   14.4542         0
1307                   Zakarian, Mr. Ortin      0    7.2250         0

[654 rows x 4 columns]

In [304]:
# boolean filtering  = filtering the recoreds from the dataset based on condition
# syntex = var [condition]

In [305]:
df [df['sex'] == 'male']

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [306]:
df [df['sex'] == 'female']

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [307]:
df['name'][df['sex']== 'female']

0                         Allen, Miss. Elisabeth Walton
2                          Allison, Miss. Helen Loraine
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
6                     Andrews, Miss. Kornelia Theodosia
8         Appleton, Mrs. Edward Dale (Charlotte Lamson)
                             ...
1286    Whabee, Mrs. George Joseph (Shawneene Abi-Saab)
1290                   Wilkes, Mrs. James (Ellen Needs)
1300            Yasbeck, Mrs. Antoni (Selini Alexander)
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
Name: name, Length: 466, dtype: object

In [308]:
df[(df['sex']== 'female') &  (df['age'] > 18) ]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1267,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S,0
1276,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,0
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1

In [309]:
df[(df['sex']== 'female') &  (df['age'] > 18) & (df['survived'] == 1) ]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1223,3,"Stanley, Miss. Amy Zillah Elsie",female,23.0,0,0,CA. 2314,7.5500,NaN,S,1
1258,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,2650,15.2458,NaN,C,1
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1

In [310]:
df[(df['sex']== 'female') &  (df['embarked'] == 'S') ]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1267,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S,0
1273,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S,0
1276,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,0
1279,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,0
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1

In [311]:
df[(df['sex']== 'female') &  (df['embarked'] == 'S') & (df['age'] > 30)  &  (df['survived'] == 0)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
286,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.0,1,0,PC 17483,221.7792,C55 C57,S,0
365,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.0,1,0,244252,26.0000,NaN,S,0
411,2,"Funk, Miss. Annie Clemmer",female,38.0,0,0,237671,13.0000,NaN,S,0
456,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.0,1,0,24065,26.0000,NaN,S,0
490,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S,0
610,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S,0
626,3,"Andersson, Miss. Ida Augusta Margareta",female,38.0,4,2,347091,7.7750,NaN,S,0
632,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.0,1,5,347082,31.2750,NaN,S,0
811,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,NaN,S,0
832,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,1,6,CA 2144,46.9000,NaN,S,0
939,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.0,0,2,350405,12.1833,NaN,S,0
943,3,"Laitinen, Miss. Kristina Sofia",female,37.0,0,0,4135,9.5875,NaN,S,0
967,3,"Lindblom, Miss. Augusta Charlotta",female,45.0,0,0,347073,7.7500,NaN,S,0
1086,3,"Olsson, Miss. Elina",female,31.0,0,0,350407,7.8542,NaN,S,0
1106,3,"Panula, Mrs. Juha (Maria Emilia Ojala)",female,41.0,0,5,3101295,39.6875,NaN,S,0
1153,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S,0
1158,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,NaN,S,0
1211,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S,0
1276,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,0

In [312]:
df[df['age'].isnull()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
40,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,0
46,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,0
59,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1293,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S,0
1297,3,"Wiseman, Mr. Phillippe",male,NaN,0,0,A/4. 34244,7.2500,NaN,S,0
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [313]:
df[df['cabin'].isnull()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
23,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C,1
25,1,"Birnbaum, Mr. Jakob",male,25.0,0,0,13905,26.0000,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [314]:
df[df['embarked'].isnull()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
168,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN,1
284,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN,1

In [315]:
df[df['survived'].isnull()]

Empty DataFrame
Columns: [pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, survived]
Index: []

In [316]:
df[df['age'].isna()] # null and na both will give same output

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
40,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,0
46,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,0
59,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1293,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S,0
1297,3,"Wiseman, Mr. Phillippe",male,NaN,0,0,A/4. 34244,7.2500,NaN,S,0
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [317]:
df[df['age'].notnull()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1301,3,"Youseff, Mr. Gerious",male,45.5000,0,0,2628,7.2250,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [318]:
df[df['age'].notna()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1301,3,"Youseff, Mr. Gerious",male,45.5000,0,0,2628,7.2250,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [319]:
#
df[(df['survived']==1) & (df['age'].isnull()) & (df['embarked']=='S')]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
69,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,113505,55.0000,E33,S,1
107,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S,1
121,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S,1
152,1,"Hawksford, Mr. Walter James",male,NaN,0,0,16988,30.0000,D45,S,1
176,1,"Kenyon, Mrs. Frederick R (Marion)",female,NaN,1,0,17464,51.8625,D21,S,1
235,1,"Rheims, Mr. George Alexander Lucien",male,NaN,0,0,PC 17607,39.6000,NaN,S,1
254,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S,1
256,1,"Salomon, Mr. Abraham L",male,NaN,0,0,111163,26.0000,NaN,S,1
293,1,"Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)",female,NaN,1,0,19996,52.0000,C126,S,1
320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
483,2,"Leitch, Miss. Jessie Wills",female,NaN,0,0,248727,33.0000,NaN,S,1
597,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,1
757,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,NaN,1,0,386525,16.1000,NaN,S,1
798,3,"Finoli, Mr. Luigi",male,NaN,0,0,SOTON/O.Q. 3101308,7.0500,NaN,S,1
805,3,"Foo, Mr. Choong",male,NaN,0,0,1601,56.4958,NaN,S,1
858,3,"Hee, Mr. Ling",male,NaN,0,0,1601,56.4958,NaN,S,1
872,3,"Howard, Miss. May Elizabeth",female,NaN,0,0,A. 2. 39186,8.0500,NaN,S,1
874,3,"Hyman, Mr. Abraham",male,NaN,0,0,3470,7.8875,NaN,S,1
887,3,"Johannesen-Bratthammer, Mr. Bernt",male,NaN,0,0,65306,8.1125,NaN,S,1
945,3,"Lam, Mr. Ali",male,NaN,0,0,1601,56.4958,NaN,S,1
1033,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S,1
1159,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S,1
1247,3,"Thorneycroft, Mrs. Percival (Florence Kate White)",female,NaN,1,0,376564,16.1000,NaN,S,1

In [320]:
#
df[(df['sex']=='female') & (df['ticket'] > '20000')]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
17,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C,1
23,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [321]:
df[(df['cabin'].isnull()) & (df['survived'] == 1)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
23,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C,1
35,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C,1
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
48,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1277,3,"Vartanian, Mr. David",male,22.0,0,0,2658,7.2250,NaN,C,1
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1

In [322]:
# DATA CLEANING  the process of removing unwanted or not related data from dataset based on user requiment
# there 13 steps in data cleaning
##for that the column name should be in the form of dictionary where key represents old column name and value represents new column name
#  step 1 remaing the column name
# syntax:
    # dict ={'oldcol1':'newcol1','oldcol2':'newcol2','oldcol....n':'newcol....n' }
    # df.RENAME(columns = dict , inplace = True) inplace which is use to save the data parmanetly
    #

In [323]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='latin-1') # encode is read the data which is in other formate

In [324]:
update = {'Janeiro':'jan','Fevereiro':'feb','Março':'mar','Abril':'apr','Maio':'may','Junho':'jun','Julho':'jul','Agosto':'aug','Setembro':'sep','Outubro':'oct','Novembro':'nov','Dezembro':'dec'}
df.rename(columns = {'ano':'year','mes':'month','estado':'state','numero':'number_of_fires','encontro':'date'} , inplace=True)
df['month'] = df['month'].map(update)

In [325]:
df

      year month      state number_of_fires      date
0     1998   jan       Acre         0 Fires  1/1/1998
1     1999   jan       Acre         0 Fires  1/1/1999
2     2000   jan       Acre         0 Fires  1/1/2000
3     2001   jan       Acre         0 Fires  1/1/2001
4     2002   jan       Acre         0 Fires  1/1/2002
...    ...   ...        ...             ...       ...
6449  2012   dec  Tocantins             128  1/1/2012
6450  2013   dec  Tocantins              85  1/1/2013
6451  2014   dec  Tocantins             223  1/1/2014
6452  2015   dec  Tocantins             373  1/1/2015
6453  2016   dec  Tocantins             119  1/1/2016

[6454 rows x 5 columns]

In [413]:
data ={'ano':'year','mes':'month','estado':'state','numero':'number_of_fires','encontro':'date'}
df.rename(columns = data , inplace=True)

In [414]:
df.columns

Index(['month', 'date', 'number_of_fires', 'year', 'state'], dtype='object')

In [328]:
df

      year month      state number_of_fires      date
0     1998   jan       Acre         0 Fires  1/1/1998
1     1999   jan       Acre         0 Fires  1/1/1999
2     2000   jan       Acre         0 Fires  1/1/2000
3     2001   jan       Acre         0 Fires  1/1/2001
4     2002   jan       Acre         0 Fires  1/1/2002
...    ...   ...        ...             ...       ...
6449  2012   dec  Tocantins             128  1/1/2012
6450  2013   dec  Tocantins              85  1/1/2013
6451  2014   dec  Tocantins             223  1/1/2014
6452  2015   dec  Tocantins             373  1/1/2015
6453  2016   dec  Tocantins             119  1/1/2016

[6454 rows x 5 columns]

In [329]:
#step 2  removeing the dupicate
# syntex
  # df.drop_duplicate(inplace=True)
da = pd.DataFrame({
    'name' :['A','B','C','A','B','C'],
    'rollno':[29,39,45,29,11,4],
    'marks':[63,34,75,63,81,78]
})
da

  name  rollno  marks
0    A      29     63
1    B      39     34
2    C      45     75
3    A      29     63
4    B      11     81
5    C       4     78

In [330]:
da.drop_duplicates(inplace=True)

In [331]:
da

  name  rollno  marks
0    A      29     63
1    B      39     34
2    C      45     75
4    B      11     81
5    C       4     78

In [332]:
# step 3 changing the data present in a particular  column
# syntex :
  # df['col_name'] = df['col_name'].map(dict)
  #map: use perform same task for entaire dataset
df.head()

   year month state number_of_fires      date
0  1998   jan  Acre         0 Fires  1/1/1998
1  1999   jan  Acre         0 Fires  1/1/1999
2  2000   jan  Acre         0 Fires  1/1/2000
3  2001   jan  Acre         0 Fires  1/1/2001
4  2002   jan  Acre         0 Fires  1/1/2002

In [333]:
# change the month to jan
df['month'].unique()

array(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep',
       'oct', 'nov', 'dec'], dtype=object)

In [418]:
update = {'Janeiro':'jan','Fevereiro':'feb','Março':'mar','Abril':'apr','Maio':'may','Junho':'jun','Julho':'jul','Agosto':'aug','Setembro':'sep','Outubro':'oct','Novembro':'nov','Dezembro':'dec'}
df['mes'] = df['mes'].map(update)

df

KeyError: 'mes'

In [335]:
display(df)

      year month      state number_of_fires      date
0     1998   NaN       Acre         0 Fires  1/1/1998
1     1999   NaN       Acre         0 Fires  1/1/1999
2     2000   NaN       Acre         0 Fires  1/1/2000
3     2001   NaN       Acre         0 Fires  1/1/2001
4     2002   NaN       Acre         0 Fires  1/1/2002
...    ...   ...        ...             ...       ...
6449  2012   NaN  Tocantins             128  1/1/2012
6450  2013   NaN  Tocantins              85  1/1/2013
6451  2014   NaN  Tocantins             223  1/1/2014
6452  2015   NaN  Tocantins             373  1/1/2015
6453  2016   NaN  Tocantins             119  1/1/2016

[6454 rows x 5 columns]

In [336]:
df['month'].unique()# it will display all the unique value in one particular column

array([nan], dtype=object)

In [337]:
# if we want display all the unique value in all the columns value
# here we use comprehension
[{i:df[i].unique() for i in df.columns}]
# or
#we can use for loop
# for i in df.columns:
    #print (df[i].unique())

[{'year': array([1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
         2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]),
  'month': array([nan], dtype=object),
  'state': array(['Acre', 'alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
         'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
         'Mato Grosso', 'Minas Gerais', 'pará', 'Paraiba', 'Pernambuco',
         'Piau', 'Rio', 'rondonia', 'Roraima', 'Santa Catarina',
         'Sao Paulo', 'Sergipe', 'Tocantins'], dtype=object),
  'number_of_fires': array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
        dtype=object),
  'date': array(['1/1/1998', '1/1/1999', '1/1/2000', '1/1/2001', '1/1/2002',
         '1/1/2003', '1/1/2004', '1/1/2005', '1/1/2006', '1/1/2007',
         '1/1/2008', '1/1/2009', '1/1/2010', '1/1/2011', '1/1/2012',
         '1/1/2013', '1/1/2014', '1/1/2015', '1/1/2016', '1/1/2017'],
        dtype=object)}]

In [408]:
# step 4: removing the unwanted data present in the column
# syntax
   #df['col_name'] = df['col_name'].str.strip('unwanted data')

df['number_of_fires'] = df['number_of_fires'].str.strip(' Fires')
df.head(10)

KeyError: 'number_of_fires'

In [339]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='latin-1') # encode is read the data which is in other formate

df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [340]:
update = {'Janeiro':'jan','Fevereiro':'feb','Março':'mar','Abril':'apr','Maio':'may','Junho':'jun','Julho':'jul','Agosto':'aug','Setembro':'sep','Outubro':'oct','Novembro':'nov','Dezembro':'dec'}
df['mes'] = df['mes'].map(update)

df

       ano  mes     estado   numero  encontro
0     1998  jan       Acre  0 Fires  1/1/1998
1     1999  jan       Acre  0 Fires  1/1/1999
2     2000  jan       Acre  0 Fires  1/1/2000
3     2001  jan       Acre  0 Fires  1/1/2001
4     2002  jan       Acre  0 Fires  1/1/2002
...    ...  ...        ...      ...       ...
6449  2012  dec  Tocantins      128  1/1/2012
6450  2013  dec  Tocantins       85  1/1/2013
6451  2014  dec  Tocantins      223  1/1/2014
6452  2015  dec  Tocantins      373  1/1/2015
6453  2016  dec  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [341]:
df

       ano  mes     estado   numero  encontro
0     1998  jan       Acre  0 Fires  1/1/1998
1     1999  jan       Acre  0 Fires  1/1/1999
2     2000  jan       Acre  0 Fires  1/1/2000
3     2001  jan       Acre  0 Fires  1/1/2001
4     2002  jan       Acre  0 Fires  1/1/2002
...    ...  ...        ...      ...       ...
6449  2012  dec  Tocantins      128  1/1/2012
6450  2013  dec  Tocantins       85  1/1/2013
6451  2014  dec  Tocantins      223  1/1/2014
6452  2015  dec  Tocantins      373  1/1/2015
6453  2016  dec  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [342]:
# step 5 : Apply inbuilt function on particular column
#syntex :
  # df['col_name'] = df[col_name].str.fname(args)

df['mes'].unique()

array(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep',
       'oct', 'nov', 'dec'], dtype=object)

In [343]:
df

       ano  mes     estado   numero  encontro
0     1998  jan       Acre  0 Fires  1/1/1998
1     1999  jan       Acre  0 Fires  1/1/1999
2     2000  jan       Acre  0 Fires  1/1/2000
3     2001  jan       Acre  0 Fires  1/1/2001
4     2002  jan       Acre  0 Fires  1/1/2002
...    ...  ...        ...      ...       ...
6449  2012  dec  Tocantins      128  1/1/2012
6450  2013  dec  Tocantins       85  1/1/2013
6451  2014  dec  Tocantins      223  1/1/2014
6452  2015  dec  Tocantins      373  1/1/2015
6453  2016  dec  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [344]:
df['mes'] = df['mes'].str.upper()

In [345]:
df

       ano  mes     estado   numero  encontro
0     1998  JAN       Acre  0 Fires  1/1/1998
1     1999  JAN       Acre  0 Fires  1/1/1999
2     2000  JAN       Acre  0 Fires  1/1/2000
3     2001  JAN       Acre  0 Fires  1/1/2001
4     2002  JAN       Acre  0 Fires  1/1/2002
...    ...  ...        ...      ...       ...
6449  2012  DEC  Tocantins      128  1/1/2012
6450  2013  DEC  Tocantins       85  1/1/2013
6451  2014  DEC  Tocantins      223  1/1/2014
6452  2015  DEC  Tocantins      373  1/1/2015
6453  2016  DEC  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [346]:
# step 6 : how to handel the missing values
# syntex

df2 = pd.DataFrame(
    {
        'name': [np.nan,'B',np.nan,'A'],
        'roll_no':[np.nan,2,'None',1],
        'marks':[np.nan,60,70,20]

    })
display(df2)

  name roll_no  marks
0  NaN     NaN    NaN
1    B       2   60.0
2  NaN    None   70.0
3    A       1   20.0

In [367]:
# 1 deleting all the nan values here we use 2 methods 'ANY' and 'ALL'
#syntax: df.dropna(inplace = True)

df2['name']

1    B
3    A
Name: name, dtype: object

In [348]:
df2['name'].dropna(inplace=True)

In [349]:
df2['name']

0    NaN
1      B
2    NaN
3      A
Name: name, dtype: object

In [350]:
df2['marks'].dropna(inplace=True)

In [351]:
df2['marks'] #here we are not droping any values , to overcome that we use next up

0     NaN
1    60.0
2    70.0
3    20.0
Name: marks, dtype: float64

In [352]:
df2

  name roll_no  marks
0  NaN     NaN    NaN
1    B       2   60.0
2  NaN    None   70.0
3    A       1   20.0

In [353]:
# if you want to drop the entire row if all the values are NaN

df2.dropna(how='all',inplace=True)  #it will remove entries row if the value in NaN
df2

  name roll_no  marks
1    B       2   60.0
2  NaN    None   70.0
3    A       1   20.0

In [354]:
# if you want to delete row oif it has at least one NaN in it we use
df2.dropna(how='any',inplace=True)  #it will remove entries row if the value in NaN
df2

  name roll_no  marks
1    B       2   60.0
3    A       1   20.0

In [355]:
# 2 filling nan value either with 0 or mean or median

df4 = pd.DataFrame(
    {
    'name':['A','B',np.nan,'A',np.nan,'C'],
    'roll_no':[1,2,'None',1,np.nan,3], #'None' is in str formate thats why it is not NONE ,now it is srt
    'marks':[np.nan,60,70,20,40,50]
    })
df4

  name roll_no  marks
0    A       1    NaN
1    B       2   60.0
2  NaN    None   70.0
3    A       1   20.0
4  NaN     NaN   40.0
5    C       3   50.0

In [356]:
# np.nan are the real missing values
#forward fill (ffill) ---- replace NaN with the previous not-null value in the column value, means in name col 2 row it will occupy B in place af Nan

In [357]:
df4['name']

0      A
1      B
2    NaN
3      A
4    NaN
5      C
Name: name, dtype: object

In [358]:
df4['name'].ffill()

0    A
1    B
2    B
3    A
4    A
5    C
Name: name, dtype: object

In [359]:
#backward fill ---> replaces NaN with the next non-null
# it will work under cyclic manner if last value will be replaced by first value only when last cell is Nan

In [360]:
df4['name']

0      A
1      B
2    NaN
3      A
4    NaN
5      C
Name: name, dtype: object

In [361]:
df4['name'].bfill()

0    A
1    B
2    A
3    A
4    C
5    C
Name: name, dtype: object

In [362]:
#mean()
a=df4['marks'].mean()
a

np.float64(48.0)

In [363]:
df4['marks'].fillna(a) #fillna use to assign the value for missing data with mean value which is stored in a variable

0    48.0
1    60.0
2    70.0
3    20.0
4    40.0
5    50.0
Name: marks, dtype: float64

In [364]:
# median ()
b = df2['marks'].median()
b

40.0

In [365]:
df4['marks'].fillna(b)  #fillna use to assign the value for missing data with median  value which is stored in b variable

0    40.0
1    60.0
2    70.0
3    20.0
4    40.0
5    50.0
Name: marks, dtype: float64

In [375]:
# step 7 : used to changing the datatype of particular column
# syntex
  #df['col name'] = df['col name'] .astype('datatype')  ---datatype we can spacify the datatype which we want in output
df['encontro']

0       1/1/1998
1       1/1/1999
2       1/1/2000
3       1/1/2001
4       1/1/2002
          ...
6449    1/1/2012
6450    1/1/2013
6451    1/1/2014
6452    1/1/2015
6453    1/1/2016
Name: encontro, Length: 6454, dtype: object

In [380]:
df['encontro'] = df['encontro'].astype('str')

In [381]:
df['encontro'] # here we will get datatype is object bcz str is also part of object

0       1/1/1998
1       1/1/1999
2       1/1/2000
3       1/1/2001
4       1/1/2002
          ...
6449    1/1/2012
6450    1/1/2013
6451    1/1/2014
6452    1/1/2015
6453    1/1/2016
Name: encontro, Length: 6454, dtype: object

In [384]:
df5= pd.DataFrame({
    'name' :['A','B','C','D','E','F'],
    'rollno':[29,39,45,29,11,4],
    'marks':[63,34,75,63,81,78]
})
df5

  name  rollno  marks
0    A      29     63
1    B      39     34
2    C      45     75
3    D      29     63
4    E      11     81
5    F       4     78

In [387]:
df5['marks']

0    63
1    34
2    75
3    63
4    81
5    78
Name: marks, dtype: int64

In [392]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   rollno  6 non-null      int64
 2   marks   6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [393]:
df5['marks'] = df5['marks'].astype('Int64')
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   rollno  6 non-null      int64
 2   marks   6 non-null      Int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 282.0+ bytes

In [400]:
# Step 8 : Rearrange the order of column  # here we target the index of column
# syntex :
  # new_order = [i1,i2,....,in]
    # df = df[df.columns[new_order]]

In [401]:
df.head()

    ano  mes estado   numero  encontro
0  1998  JAN   Acre  0 Fires  1/1/1998
1  1999  JAN   Acre  0 Fires  1/1/1999
2  2000  JAN   Acre  0 Fires  1/1/2000
3  2001  JAN   Acre  0 Fires  1/1/2001
4  2002  JAN   Acre  0 Fires  1/1/2002

In [406]:
df6 =df.head()

In [407]:
new_order = [4,3,2,1,0]
df6 = df6[df6.columns[new_order]]
df6

  estado   ano   numero  encontro  mes
0   Acre  1998  0 Fires  1/1/1998  JAN
1   Acre  1999  0 Fires  1/1/1999  JAN
2   Acre  2000  0 Fires  1/1/2000  JAN
3   Acre  2001  0 Fires  1/1/2001  JAN
4   Acre  2002  0 Fires  1/1/2002  JAN

In [420]:
df

     month      date number_of_fires  year      state
0      NaN  1/1/1998         0 Fires  1998       Acre
1      NaN  1/1/1999         0 Fires  1999       Acre
2      NaN  1/1/2000         0 Fires  2000       Acre
3      NaN  1/1/2001         0 Fires  2001       Acre
4      NaN  1/1/2002         0 Fires  2002       Acre
...    ...       ...             ...   ...        ...
6449   NaN  1/1/2012             128  2012  Tocantins
6450   NaN  1/1/2013              85  2013  Tocantins
6451   NaN  1/1/2014             223  2014  Tocantins
6452   NaN  1/1/2015             373  2015  Tocantins
6453   NaN  1/1/2016             119  2016  Tocantins

[6454 rows x 5 columns]

In [422]:
update = {'Janeiro':'jan','Fevereiro':'feb','Março':'mar','Abril':'apr','Maio':'may','Junho':'jun','Julho':'jul','Agosto':'aug','Setembro':'sep','Outubro':'oct','Novembro':'nov','Dezembro':'dec'}
df['month'] = df['month'].map(update)

df

     month      date number_of_fires  year      state
0      NaN  1/1/1998         0 Fires  1998       Acre
1      NaN  1/1/1999         0 Fires  1999       Acre
2      NaN  1/1/2000         0 Fires  2000       Acre
3      NaN  1/1/2001         0 Fires  2001       Acre
4      NaN  1/1/2002         0 Fires  2002       Acre
...    ...       ...             ...   ...        ...
6449   NaN  1/1/2012             128  2012  Tocantins
6450   NaN  1/1/2013              85  2013  Tocantins
6451   NaN  1/1/2014             223  2014  Tocantins
6452   NaN  1/1/2015             373  2015  Tocantins
6453   NaN  1/1/2016             119  2016  Tocantins

[6454 rows x 5 columns]

In [436]:
#  step 9 : changing the data prasent in one particular column
#syntex :  df['col_name'] = df['col_name'].str.replace(old_value,new_value)
df['mes'].unique()

array(['jan', 'feb', 'Mar', 'apl', 'may', 'Junho', 'Julho', 'Agosto',
       'Setembro', 'Outubro', 'Novembro', 'Dezembro'], dtype=object)

In [423]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='latin-1') # encode is read the data which is in other formate

df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [424]:
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [427]:
df['mes'].unique()

array(['jan', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [428]:
df['mes'] = df['mes'].str.replace('Janeiro','jan')

In [429]:
df

       ano       mes     estado   numero  encontro
0     1998       jan       Acre  0 Fires  1/1/1998
1     1999       jan       Acre  0 Fires  1/1/1999
2     2000       jan       Acre  0 Fires  1/1/2000
3     2001       jan       Acre  0 Fires  1/1/2001
4     2002       jan       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [434]:
df['mes'] = df['mes'].str.replace('Fevereiro','feb')
df['mes'] = df['mes'].str.replace('Março','Mar')
df['mes'] = df['mes'].str.replace('Abril','apl')
df['mes'] = df['mes'].str.replace('Maio','may')

In [435]:
df['mes'].unique()

array(['jan', 'feb', 'Mar', 'apl', 'may', 'Junho', 'Julho', 'Agosto',
       'Setembro', 'Outubro', 'Novembro', 'Dezembro'], dtype=object)

In [437]:
# step 10 : droping 5the unwanted columns
# syntex : del df['col_name'] # del=delete

del df['numero']

In [438]:
df # numero column has been deleted

       ano       mes     estado  encontro
0     1998       jan       Acre  1/1/1998
1     1999       jan       Acre  1/1/1999
2     2000       jan       Acre  1/1/2000
3     2001       jan       Acre  1/1/2001
4     2002       jan       Acre  1/1/2002
...    ...       ...        ...       ...
6449  2012  Dezembro  Tocantins  1/1/2012
6450  2013  Dezembro  Tocantins  1/1/2013
6451  2014  Dezembro  Tocantins  1/1/2014
6452  2015  Dezembro  Tocantins  1/1/2015
6453  2016  Dezembro  Tocantins  1/1/2016

[6454 rows x 4 columns]